<div id="tb963TEST" style="background-color: pink;">
	<?php $_order = $this->getOrder();

	$supplierArray = array();
	$productsArray = array();
	$_items = $this->getItemsCollection();

	foreach ($_items as $_item){
		$product_id = $_item -> getProductId();
		$product=Mage::getModel("catalog/product")->load($product_id);
		$supplier = $product->getAttributeText("supplier");


		//element not inside array
		if(!in_array($supplier, $supplierArray)){
			array_push($supplierArray, $supplier);
		}

		//retrieve necessary informations
		$supplierSku = $product -> _getData("supplier_sku");
		$sku = $_item->getSku();
		$name = $_item->_getData('name');
		$qty = (int)$_item->getQtyOrdered();

		//creation of temporary array
		$tmpArray = array(
			"supplierSku" =>$supplierSku,
			"sku"=> $sku,
			"name" =>$name,
			"qty" =>$qty
			);

		//count number of elements and append new element to array
		$arrayLng = count($productsArray[$supplier]);
		$productsArray[$supplier][$arrayLng] = $tmpArray;

		//IMPORTANT: with the "unset" you clear the variable
		unset($arrayLng);
		unset($tmpArray);
	}?>


	<select id="selectTEST">
		<?php 
		foreach($supplierArray as $key => $value){
			echo "<option>".$value."</option>"; 
		}
		?>
	</select>
	<button onclick="disagio();">Generate text</button>
	<button class="js-textareacopybtn">Copy Textarea</button>
	<br />
	<br />
	<br />



	<?php 
		/*print "\n\r"."Hello,"."\n\r";
		print "Please can we place an order for:"."\n\r";

		foreach($productsArray["Contour"] as $singleProduct){
			print $singleProduct["qty"]."x ".$singleProduct["supplierSku"].": ".$singleProduct["name"]."\n\r";
		}
		

		print "\n\r";
		print "Delivery address:"."\n\r";
		print $_order->getShippingAddress()->getFormated(false);

		print "\n\r";
		print "Many thanks,"."\n\r";*/
	?>

	<textarea id="mailBody" style="background-color:gray; width:95%; height:600px" readonly>
	</textarea>



	<script>
	function disagio(){
		document.getElementById('mailBody').value = '';
		
		var e = document.getElementById("selectTEST");
		var strUser = e.options[e.selectedIndex].text;
		console.log(strUser);

		var productsArray = <?php echo json_encode($productsArray);?>;
		//console.log(productsArray);
		//console.log(productsArray["Contour"]);

		var text = "Hello,\n"
					+"\n"
					+"Please can we place an order for: "
					+"\n";
		var sltSupplier = productsArray[strUser];

		for(var i=0; i<sltSupplier.length; i++){
			text += sltSupplier[i]["qty"]+"x "
					+sltSupplier[i]["supplierSku"]+": "
					+sltSupplier[i]["name"]
					+"\n";
		};

		text += "\n"
				+"Delivery address: "
				+"\n"
				+"(currently working on this)"
				+"\n"
				+"\n"
				+"\n"
				+"Many thanks,"
				+"\n";

		document.getElementById('mailBody').value = text;
	}
	</script>

	<script>
		var copyTextareaBtn = document.querySelector('.js-textareacopybtn');

		copyTextareaBtn.addEventListener('click', function(event) {
		  var copyTextarea = document.querySelector('.mailBody');
		  copyTextarea.select();

		  try {
			var successful = document.execCommand('copy');
			var msg = successful ? 'successful' : 'unsuccessful';
			console.log('Copying text command was ' + msg);
		  } catch (err) {
			console.log('Oops, unable to copy');
		  }
		});
	</script>
</div>
<br />