<?php
$_order = $this->getOrder();

$supplierArray = array();
$productsArray = array();
$_items = $this->getItemsCollection();

foreach ($_items as $_item){
	$productOptions = array();
	$product_id = $_item -> getProductId();
	$product=Mage::getModel("catalog/product")->load($product_id);
	$supplier = $product->getAttributeText("supplier");
	$rawProductOptions = unserialize($_item->getData("product_options"));

	
	//check if "options" is present into $rawProductOptions
	if(in_array("options",array_keys($rawProductOptions))){
		//creation of custom options ("product_options") array
		foreach($rawProductOptions["options"] as $singleOption){
			$optionsArrayLng = count($productOptions);
			$tmpOptsArray = array(
				"label" => $singleOption["label"],
				"value"=> $singleOption["value"]
				);
			$productOptions[$optionsArrayLng] = $tmpOptsArray;
			unset($optsArrayLng);
			unset($tmpOptsArray);
		}
	}
	

	//element not inside array
	if(!in_array($supplier, $supplierArray)){
		array_push($supplierArray, $supplier);
	}

	//retrieve necessary informations
	$supplierSku = $product -> _getData("supplier_sku");
	$sku = $_item->getSku();
	$name = $_item->_getData('name');
	$qty = (int)$_item->getQtyOrdered();

	//creation of temporary array
	$tmpProductArray = array(
		"supplierSku" =>$supplierSku,
		"sku" => $sku,
		"name" =>$name,
		"qty" =>$qty,
		"options" =>$productOptions
		);

	
	//check if index $supplier exists, if not it will be added to the $productsArray
	if(!in_array($supplier, array_keys($productsArray))){
		$productsArray[$supplier] = array();
	}
	//count number of elements and append new element to array
	$productArrayLng = count($productsArray[$supplier]);
	$productsArray[$supplier][$productArrayLng] = $tmpProductArray;

	//IMPORTANT: with the "unset" you clear the variable
	unset($productArrayLng);
	unset($tmpProductArray);
	unset($productOptions);
};
//get shipping address
$shippingAddress = $_order->getShippingAddress()->getFormated(false);
?>
<div id="tb963CustomMail">
	<div id="buttonsRow" style="text-align: right">
		<select id="selectSupplier">
			<?php 
				foreach($supplierArray as $key => $value){
					echo "<option>".$value."</option>"; 
				}
			?>
		</select>
		<button onclick="textCreation();">Generate text</button>
		<button onclick="copyText();">Copy textarea</button>
	</div>
	<br clear:"all">


	<textarea id="mailBody" style="background-color:#F6F6F6; width:60%; height:500px" readonly>
	</textarea>


	<script>
	function textCreation(){
		//cleaning of the textarea
		document.getElementById('mailBody').value = '';
		
		var e = document.getElementById("selectSupplier");
		var chosenSupplier = e.options[e.selectedIndex].text;
		var productsArray = <?php echo json_encode($productsArray);?>;
		var shippingAddress = <?php echo json_encode($shippingAddress); ?>;
		//the replace is done three times because some \n can't be sensed the first and the second time
		shippingAddress = shippingAddress.replace(/(\n\n)/gm,"\n");
		shippingAddress = shippingAddress.replace(/(\n\n)/gm,"\n");
		shippingAddress = shippingAddress.replace(/(\n\n)/gm,"\n");

		var text = "Hello,\n"
					+"\n"
					+"Please can we place an order for: "
					+"\n";

		for(var i=0; i<productsArray[chosenSupplier].length; i++){
			if(productsArray[chosenSupplier][i]["options"].length==0){
				text += "\n"
						+productsArray[chosenSupplier][i]["qty"]+"x "
						+productsArray[chosenSupplier][i]["supplierSku"]+": "
						+productsArray[chosenSupplier][i]["name"]
						+"\n";	
			}else{
				text += "\n"
						+productsArray[chosenSupplier][i]["qty"]+"x "
						+productsArray[chosenSupplier][i]["supplierSku"]+": "
						+productsArray[chosenSupplier][i]["name"]
						+"\n";

				for(var j=0; j<productsArray[chosenSupplier][i]["options"].length; j++){
					text += "\t"
							+productsArray[chosenSupplier][i]["options"][j]["label"]
							+": "
							+productsArray[chosenSupplier][i]["options"][j]["value"]
							+"\n";
				}	
			}
		};
		text += "\n"
				+"Delivery address: \n"
				+"\n"
				+shippingAddress
				+"\n"
				+"Many thanks,"
				+"\n";
		//insert text into textarea
		document.getElementById('mailBody').value = text;
	}

	function copyText(){
		var copyTextarea = document.querySelector('#mailBody');
	  	copyTextarea.select();

	  	try {
	  		var successful = document.execCommand('copy');
			var msg = successful ? 'successful' : 'unsuccessful';
			console.log('Copying text command was ' + msg);
	  	} catch (err) {
	  		console.log('Oops, unable to copy');
	  		console.log("err:\n\n"+err);
		}
		//by the time the function addComment() will stay here, out of the try-catch, because of problems with Firefox
		addComment();
	}



	function addComment(){
		var e = document.getElementById("selectSupplier");
		var chosenSupplier = e.options[e.selectedIndex].text;

		var addcomment = new XMLHttpRequest(); //New request object

		chosenSupplier = chosenSupplier.replace(" ", "_");

		var commentPath= "<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/customMail/comment/'); ?>"+"?isAjax=true"+"&orderID="+<?php echo $_order->getId(); ?>+"&supplier="+chosenSupplier;
		
		var addcomment = new XMLHttpRequest();
		addcomment.open("get", commentPath, true);
		addcomment.setRequestHeader("Content-type","application/x-www-form-urlencoded");
		addcomment.send();
	}
	</script>
</div>
<br />